### ISSUE TITLE
Unhandled Exception in alert_manager.py

### ISSUE THREAD

**Issue by johnfromthefuture** [simcen/alert_manager#142]
Exception happens during the incident auto-resolve process:
```
Traceback (most recent call last):
	File "/opt/splunk/sh/etc/apps/alert_manager/bin/alert_manager.py", line 437, in <module>
	setIncidentsAutoResolved(search_name, job_id, config['title'], settings.get('index'), sessionKey)

	File "/opt/splunk/sh/etc/apps/alert_manager/bin/alert_manager.py", line 43, in setIncidentsAutoResolved

	incidents = getRestData(uri, sessionKey, output_mode = 'default')

	File "/opt/splunk/sh/etc/apps/alert_manager/bin/alert_manager.py", line 229, in getRestData
	returnData = json.loads(serverContent)

	raise ValueError("No JSON object could be decoded")
```

Line 229, replaced `returnData = json.loads(serverContent)` with
```
    try:
        returnData = json.loads(serverContent)
    except:
        log.info('An error occurred or no data was returned from the server query.')
        returnData = []
```

**Comment by simcen** [comment]
Solved in b535ea1. Thx for the report
